[package]
name = "tortuga"
version = "0.1.0"
authors = ["expectocode <expectocode@gmail.com>", "Lonami Exo <totufals@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atom_syndication = { version = "0.9.0", default-features = false }
chrono = "0.4.11"
pulldown-cmark = "0.7.1"
